"""init

Revision ID: c9d6f36ee963
Revises:
Create Date: 2025-08-08 11:58:28.108483+08:00

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c9d6f36ee963"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("span_id", sa.String(), nullable=True),
        sa.Column("parent_span_id", sa.String(), nullable=True),
        sa.Column("trace_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="ddd_service",
    )
    op.create_index(
        "ix_ddd_service_domain_event_body",
        "domain_event",
        ["body"],
        unique=False,
        schema="ddd_service",
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_ddd_service_domain_event_name"), "domain_event", ["name"], unique=False, schema="ddd_service"
    )
    op.create_table(
        "your_aggregate",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("your_value_object", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("operation_histories", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("creator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="ddd_service",
    )
    op.create_table(
        "your_aggregate_archive",
        sa.Column("archive_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("id", sa.String(), nullable=True),
        sa.Column("doer", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("event_name", sa.String(), nullable=True),
        sa.Column("event_span_id", sa.String(), nullable=True),
        sa.Column("event_trace_id", sa.String(), nullable=True),
        sa.Column("your_value_object", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("operation_histories", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("creator", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
        schema="ddd_service",
    )
    op.create_index(
        op.f("ix_ddd_service_your_aggregate_archive_id"),
        "your_aggregate_archive",
        ["id"],
        unique=False,
        schema="ddd_service",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ddd_service_your_aggregate_archive_id"), table_name="your_aggregate_archive", schema="ddd_service"
    )
    op.drop_table("your_aggregate_archive", schema="ddd_service")
    op.drop_table("your_aggregate", schema="ddd_service")
    op.drop_index(op.f("ix_ddd_service_domain_event_name"), table_name="domain_event", schema="ddd_service")
    op.drop_index(
        "ix_ddd_service_domain_event_body", table_name="domain_event", schema="ddd_service", postgresql_using="gin"
    )
    op.drop_table("domain_event", schema="ddd_service")
    # ### end Alembic commands ###
